---
- name: Add gpg key google
  ansible.builtin.apt_key:
    url: "{{ google_chrome_gpg_key }}"
    state: present

- name: Add google repo
  ansible.builtin.apt_repository:
    repo: "{{ google_chrome_repo }}"
    state: present

- name: Update cache apt
  ansible.builtin.apt:
    update_cache: yes

- name: Install Google Chrome
  ansible.builtin.apt:
    name: google-chrome-stable
    state: present