---
- name: Installer les dépendances nécessaires pour Zephyr
  become: true
  apt:
    name:
      - git
      - cmake
      - ninja-build
      - gperf
      - ccache
      - dfu-util
      - device-tree-compiler
      - wget
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-tk
      - python3-full
      - python3-wheel
      - python3-venv
      - xz-utils
      - file
      - make
      - gcc
      - gcc-multilib
      - g++-multilib
      - libsdl2-dev
      - libmagic1
    state: present
    update_cache: yes

- name: Install west
  include_tasks: west.yml
- name: Install sdk
  include_tasks: sdk.yml
- name: Test
  include_tasks: test.yml