- name: Télécharger le Zephyr SDK
  become: true
  get_url:
    url: "https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.3/zephyr-sdk-0.16.3_linux-x86_64.tar.xz"
    dest: "/opt/zephyr-sdk-0.16.3_linux-x86_64.tar.xz"
    checksum: "sha256:https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.3/sha256.sum"

- name: Extraire le Zephyr SDK
  become: true
  unarchive:
    src: "/opt/zephyr-sdk-0.16.3_linux-x86_64.tar.xz"
    dest: "/opt"
    remote_src: yes
    creates: "/opt/zephyr-sdk-0.16.3"

- name: Exécuter le script de configuration du SDK Zephyr
  become: true
  command:
    cmd: "./setup.sh"
    chdir: "/opt/zephyr-sdk-0.16.3"

- name: Installer les règles udev pour OpenOCD
  become: true
  copy:
    src: "/opt/zephyr-sdk-0.16.3/sysroots/x86_64-pokysdk-linux/usr/share/openocd/contrib/60-openocd.rules"
    dest: "/etc/udev/rules.d/60-openocd.rules"

- name: Recharger les règles udev
  become: true
  command: udevadm control --reload